#!/bin/bash

CONFIG_FILE=horolog.toml
SRC_CONFIG=$(dirname "$0")/cfg
DST_CONFIG=/etc

SERVICE_FILE=horolog.service
SERVICE_NAME=horolog.service
SRC_SERVICE_FILE=$(dirname "$0")/systemd
DST_SERVICE_FILE=/etc/systemd/system

if [ "$(id --user)" -ne 0 ];
  then echo "Please run as root!"
  exit 1
fi

set -e

install()
{
  cp --verbose "${SRC_CONFIG}/${CONFIG_FILE}" ${DST_CONFIG}/
  cp --verbose "${SRC_SERVICE_FILE}/${SERVICE_FILE}" ${DST_SERVICE_FILE}/

  local user
  user="$(whoami)"

  local path_bin
  path_bin="/home/${SUDO_USER}/.local/bin/horolog"

  sed -i "s/username/${user}/" ${DST_SERVICE_FILE}/${SERVICE_FILE}
  sed -i "s@execstart@${path_bin} loop@" ${DST_SERVICE_FILE}/${SERVICE_FILE}

  systemctl daemon-reload
  systemctl enable ${SERVICE_NAME}
}

uninstall()
{
  systemctl stop ${SERVICE_NAME}
  systemctl disable ${SERVICE_NAME}
  systemctl daemon-reload

  local path_bin
  path_bin="/home/${SUDO_USER}/.local/bin/horolog"

  rm --force --verbose ${DST_SERVICE_FILE}/${SERVICE_FILE}
  rm --force --verbose ${DST_CONFIG}/${CONFIG_FILE}
  rm --force --verbose "${path_bin}"
}

echo "Select setup type:"
echo "[1] -> Install product"
echo "[2] -> Uninstall product"
echo -n "> "
read -r SETUP_TYPE
echo

if [ "$SETUP_TYPE" = 1 ]
then
  install
elif [ "$SETUP_TYPE" = 2 ]
then
  uninstall
else
  echo "Unrecognized setup option!"
  exit 1
fi
