# Horologian configuration file
# See https://github.com/dsw7/Horologion

[times]

[times.wake]
# When the machine should wake up

# Specify hour [0-23]
time-wake-hour = 8

# Specify minute [0-59]
time-wake-minute = 0

[times.run]
# When the machine should run commands

# Specify hour [0-23]
time-cmd-hour = 8

# Specify minute [0-59]
time-cmd-minute = 1

[times.sleep]
# When the machine should sleep

# Specify hour [0-23]
time-sleep-hour = 8

# Specify minute [0-59]
time-sleep-minute = 2

[suspend]
# Select one of:
# none    -> Do nothing (useful for troubleshooting)
# standby -> Power-On Suspend    ACPI state S1
# mem     -> Suspend-to-RAM      ACPI state S3
# disk    -> Suspend-to-Disk     ACPI state S4

# System will exit if any of standby, mem or disk is not supported
# See https://www.kernel.org/doc/Documentation/power/states.txt for more information
type = "mem"

[targets]
# Specify targets following target_1 ... target_n

target_1 = "whoami && id $(whoami)"
target_2 = "sleep 2"
target_3 = "sleep 3"
# target_4 = "ls -ltr"
# ...
